
//----------------------------------------------------
// The following code was generated by CUP v0.11a beta 20060608
// Tue Oct 05 22:15:01 MDT 2021
//----------------------------------------------------

package Main;

/** CUP generated class containing symbol constants. */
public class sym {
  /* terminals */
  public static final int When = 58;
  public static final int Obj = 3;
  public static final int Doorbell = 93;
  public static final int PortD = 12;
  public static final int Menor = 62;
  public static final int PortC = 11;
  public static final int Coma = 5;
  public static final int Room = 101;
  public static final int PortB = 10;
  public static final int PortA = 9;
  public static final int UnlockAt = 36;
  public static final int True = 97;
  public static final int Receive = 52;
  public static final int Punto = 4;
  public static final int Default = 59;
  public static final int IsOut = 47;
  public static final int Home = 7;
  public static final int For = 54;
  public static final int Numero_Flotante = 91;
  public static final int Unlock = 30;
  public static final int SmartCamera = 89;
  public static final int Else = 57;
  public static final int Start = 17;
  public static final int Resta = 68;
  public static final int Int = 48;
  public static final int IsOpen = 32;
  public static final int Color = 24;
  public static final int This = 92;
  public static final int Suma = 67;
  public static final int ERROR = 85;
  public static final int Parentesis_der = 76;
  public static final int Cadena = 86;
  public static final int Inc = 73;
  public static final int LightMode = 23;
  public static final int Set = 16;
  public static final int Program = 90;
  public static final int FaceCheck = 94;
  public static final int Corchete_der = 78;
  public static final int Llave_der = 80;
  public static final int Off = 20;
  public static final int Alarm = 44;
  public static final int IsClose = 33;
  public static final int ERROR3 = 102;
  public static final int ERROR2 = 87;
  public static final int Asignacion = 60;
  public static final int Enable = 13;
  public static final int Close = 28;
  public static final int IsMove = 43;
  public static final int New = 27;
  public static final int Comillas_simples = 6;
  public static final int Menor_igual = 65;
  public static final int IsLock = 34;
  public static final int Or = 72;
  public static final int And = 71;
  public static final int Open = 26;
  public static final int Mayor_igual = 64;
  public static final int On = 21;
  public static final int Mayor = 63;
  public static final int If = 56;
  public static final int EOF = 0;
  public static final int Bool = 51;
  public static final int Door = 25;
  public static final int Division = 70;
  public static final int Numero_Euler_Flotante = 84;
  public static final int Light = 19;
  public static final int Numero_Euler = 83;
  public static final int Display = 53;
  public static final int Initialize = 8;
  public static final int Temp = 39;
  public static final int Parentesis_izq = 75;
  public static final int error = 1;
  public static final int False = 98;
  public static final int Numero_Entero = 82;
  public static final int Diferente = 66;
  public static final int LightRGB = 22;
  public static final int Float = 50;
  public static final int Record = 40;
  public static final int Device = 45;
  public static final int IsUnlock = 35;
  public static final int Move = 42;
  public static final int StopRec = 41;
  public static final int Identificador = 81;
  public static final int Shutdown = 18;
  public static final int Corchete_izq = 77;
  public static final int Window = 31;
  public static final int Llave_izq = 79;
  public static final int Lock = 29;
  public static final int IsIn = 46;
  public static final int IsOn = 99;
  public static final int Camera = 38;
  public static final int AsignacionArrow = 88;
  public static final int SaveFace = 95;
  public static final int Ac = 15;
  public static final int Text = 49;
  public static final int DeleteFace = 96;
  public static final int Dec = 74;
  public static final int Igual = 61;
  public static final int Then = 100;
  public static final int While = 55;
  public static final int LockAt = 37;
  public static final int Multiplicacion = 69;
  public static final int PComa = 2;
  public static final int GetTemp = 14;
}

